# Generated by Django 3.2.7 on 2021-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
