# Generated by Django 3.2.7 on 2021-09-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
